#!/bin/sh -e

BOOTCOUNT_ENV=1

if [ -f /etc/default/updatehub-active ]; then
    . /etc/default/updatehub-active
fi

active=$1

case "$active" in
    0|1)
        # By default, machines use the bootcount inside environment so
        # we must set 'upgrade_available' to force U-Boot to count
        # the boot attempts.
        if [ "$BOOTCOUNT_ENV" = "1" ]; then
            fw_setenv upgrade_available 1
        fi

        fw_setenv updatehub_active "$1"
        exit $?
        ;;
    *)
        exit 1
        ;;
esac
