#!/bin/sh -e

BOOTCOUNT_ENV=1

active_set_prepare() {
    :
}

active_set_finish() {
    :
}

log() {
    logger -t updatehub "updatehub-active-set: $@"
}

setenv() {
    log "setting variable $1 to $2"
    fw_setenv "$1" "$2"
    log "variable $1 is now $2"
}

if [ -f /etc/default/updatehub-active ]; then
    . /etc/default/updatehub-active
fi

active=$1

case "$active" in
    0|1)
        # By default, machines use the bootcount inside environment so
        # we must set 'upgrade_available' to force U-Boot to count
        # the boot attempts. We also need to set 'bootcount' to 0 to ensure
        # a proper initialization.
        if [ "$BOOTCOUNT_ENV" = "1" ]; then
            active_set_prepare
            setenv upgrade_available 1
            setenv bootcount 0
            active_set_finish
        fi

        active_set_prepare
        setenv updatehub_active "$1"
        active_set_finish
        exit $?
        ;;
    *)
        exit 1
        ;;
esac
