#!/bin/sh -e

BOOTCOUNT_ENV=1

active_validated_prepare() {
    :
}

active_validated_finish() {
    :
}

log() {
    logger -t updatehub "updatehub-active-validated: $@"
}

setenv() {
    log "setting variable $1 to $2"
    fw_setenv "$1" "$2"
    log "variable $1 is now $2"
}

if [ -f /etc/default/updatehub-active ]; then
    . /etc/default/updatehub-active
fi

# By default, machines use the bootcount inside environment so we must
# reset 'upgrade_available' so U-Boot stop counting the boots
if [ "$BOOTCOUNT_ENV" = "1" ]; then
    active_validated_prepare
    setenv upgrade_available 0
    active_validated_finish
    exit $?
fi

exit 0
