#!/bin/sh -e

active_get_prepare() {
    :
}

active_get_finish() {
    :
}

if [ -f /etc/default/updatehub-active ]; then
    . /etc/default/updatehub-active
fi

active_get_prepare
fw_printenv -n updatehub_active
active_get_finish

exit 0
